version: '3'

services:
  mysql: 
    image: mysql:5.7
    volumes: 
      - ./db_data:/var/lib/mysql
    restart: always
    ports: 
      - 8081:3306
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress
    volumes: 
      - ./wordpress_files:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql:mysql 
    ports:
      - 8080:80 
    restart: always
    environment: 
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment: 
      PMA_HOST: mysql # allow acces to phpmyadmin from localhost, relation with mysql
    ports:
      - "8082:80"
    restart: always
